# Generated by Django 5.2 on 2026-01-17 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name must be 2-100 characters', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(help_text='Valid email format required', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number can only contain digits, spaces, +, -, (, )', regex='^[\\d\\s\\-\\+\\(\\)]+$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
